### PR TITLE
ISSUE_1 - a new title, a new hope

### LINKED ISSUE #1: testing actions
### Description

Adding the Groups feature into 3D Repo, allowing the user to create/edit/delete groups

### Goals

- [ ] Collaborators/admins can create groups
- [ ] viewers cannot create groups
- [ ] clicking on a group highlights the group objects in viewer

### Tasks

- [ ] A new Group panel
- [ ] List group component
- [ ] edit group component
- [ ] new API end point to remove groups
- [ ] New database schema for groups (present it here)

### Related Resources

MockUp : `link to mockup`
Coda doc: `link to coda`

### PR DESCRIPTION
**Pull request by keifgwinn**
This fixes [#ISSUE_1](https://github.com/keif-gwinn/3drepo.io/issues/ISSUE_1) by merging into 'STAGING'

This fixes #1

#### Test cases

Merging into 'STAGING'
[Link to ISSUE_1](https://github.com/keif-gwinn/3drepo.io/issues/ISSUE_1)

### CODE REVIEW

**Review by keifgwinn2 — CHANGES_REQUESTED** [review]
seen

**Review by keifgwinn — COMMENTED** [review]
testse

**Review by keifgwinn2 — CHANGES_REQUESTED** [review]
aha

**Review by keifgwinn2 — CHANGES_REQUESTED** [review]
testing request changes

**Review by keifgwinn — COMMENTED** [review]
test

**Review by keifgwinn2 — CHANGES_REQUESTED** [review]
test

**Review by keifgwinn2 — COMMENTED** [review]
test

**Review by keifgwinn2 — COMMENTED** [review]
test

**Review by keifgwinn2 — CHANGES_REQUESTED** [review]
check for feedback

**Review by keifgwinn2 — APPROVED** [review]
lets see this approve

**Review by keifgwinn2 — APPROVED** [review]

**Review by keifgwinn2 — COMMENTED** [review]
I see now what I was doing

**Review by keifgwinn2 — APPROVED** [review]
approvedd

**Review by keifgwinn2 — APPROVED** [review]
approved

**Review by keifgwinn2 — APPROVED** [review]
aa

**Review by keifgwinn2 — APPROVED** [review]
approved

**Review by keifgwinn2 — APPROVED** [review]
aaaa

**Review by keifgwinn2 — APPROVED** [review]
aaa

**Review by keifgwinn2 — APPROVED** [review]
looking better

**Pull request merged**
